services:
  postgres:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: